/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFiches;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rdv_medicaux_sutharsan_ranjit.Utilisateurs;

/**
 *
 * @author franjit
 */
public class Fconnexion extends javax.swing.JDialog {

    /**
     * Creates new form Fconnexion
     */
    private Utilisateurs User ;
    private Fselection fichselection;
    public Fconnexion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     public Fconnexion(java.awt.Frame parent, boolean modal, Utilisateurs u) {
        super(parent, modal);
        initComponents();
        User= u;
        jMDPpat.setVisible(false);      //on cache tous les boutons de mot de passe oublié tant qu'on ne connait pas le choix de l'utilisateur
        tfMDPpat.setVisible(false);
        jMDPprat.setVisible(false);
        tfMDPprat.setVisible(false);
        lbMDPpat.setVisible(false);
        lbMDPprat.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jConnexion = new javax.swing.JLabel();
        rbPatient = new javax.swing.JRadioButton();
        rbPraticien = new javax.swing.JRadioButton();
        jIdentifiant = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jMotdepasse = new javax.swing.JLabel();
        pfMotdepasse = new javax.swing.JPasswordField();
        jRetour = new javax.swing.JButton();
        jContinuer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMDPpat = new javax.swing.JButton();
        tfMDPpat = new javax.swing.JTextField();
        jMDPprat = new javax.swing.JButton();
        tfMDPprat = new javax.swing.JTextField();
        lbMDPprat = new javax.swing.JLabel();
        lbMDPpat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jConnexion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jConnexion.setText("Connexion");

        rbPatient.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbPatient);
        rbPatient.setText("Patient");
        rbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPatientActionPerformed(evt);
            }
        });

        rbPraticien.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbPraticien);
        rbPraticien.setText("Praticien");
        rbPraticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPraticienActionPerformed(evt);
            }
        });

        jIdentifiant.setText("Identifiant");

        tfId.setBackground(new java.awt.Color(0, 102, 102));
        tfId.setBorder(null);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jMotdepasse.setText("Mot de passe");

        pfMotdepasse.setBackground(new java.awt.Color(0, 102, 102));
        pfMotdepasse.setBorder(null);
        pfMotdepasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMotdepasseActionPerformed(evt);
            }
        });

        jRetour.setBackground(new java.awt.Color(0, 102, 102));
        jRetour.setText("Retour");
        jRetour.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jRetourMouseDragged(evt);
            }
        });
        jRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetourActionPerformed(evt);
            }
        });

        jContinuer.setBackground(new java.awt.Color(0, 102, 102));
        jContinuer.setText("Continuer");
        jContinuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinuerActionPerformed(evt);
            }
        });

        jMDPpat.setBackground(new java.awt.Color(0, 102, 102));
        jMDPpat.setText("Mot de passe oublié ?");
        jMDPpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDPpatActionPerformed(evt);
            }
        });

        jMDPprat.setBackground(new java.awt.Color(0, 102, 102));
        jMDPprat.setText("Mot de passe oublié ?");
        jMDPprat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDPpratActionPerformed(evt);
            }
        });

        lbMDPprat.setText("Saisissez le numéro de téléphone associé à votre compte et l'identifiant de votre compte");

        lbMDPpat.setText("Saisissez le numéro social associé à votre compte et l'identifiant de votre compte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jContinuer)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lbMDPprat)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMDPpat)
                    .addComponent(jConnexion)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jMDPpat)
                        .addGap(18, 18, 18)
                        .addComponent(tfMDPpat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jMDPprat)
                        .addGap(18, 18, 18)
                        .addComponent(tfMDPprat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbPatient)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jIdentifiant)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfId, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(rbPraticien)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jMotdepasse)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pfMotdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jConnexion)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPatient)
                    .addComponent(rbPraticien))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdentifiant)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMotdepasse)
                    .addComponent(pfMotdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMDPpat)
                    .addComponent(tfMDPpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbMDPpat)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMDPprat)
                    .addComponent(tfMDPprat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lbMDPprat)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRetour)
                    .addComponent(jContinuer))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Help");

        jMenuItem2.setText("Aide");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, "Veuillez sélectionner patient ou praticien puis entrer votre identifiant et mot de passe ou bien retourner à la page précédente", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jContinuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinuerActionPerformed
        int indicPraticien = 2;
        int reussite = 2;
        
        
        if (rbPraticien.isSelected()){
            indicPraticien=0;
            reussite = User.connexion(indicPraticien, tfId.getText(), pfMotdepasse.getText());
            if(reussite == 1){  //si l'utilisateur est un patient et qu'il parvient à se connecter on poursuit en affichant la fenetre suivante
                fichselection = new Fselection(this, false, indicPraticien,User);
                this.setVisible(false);
                fichselection.setVisible(true);
            }
        }
        else if (rbPatient.isSelected()){
            indicPraticien=1;
            reussite = User.connexion(indicPraticien, tfId.getText(), pfMotdepasse.getText());
            if(reussite == 1){  //si l'utilisateur est un patient et qu'il parvient à se connecter on poursuit en affichant la fenetre suivante
                fichselection = new Fselection(this, false, indicPraticien,User);
                this.setVisible(false);
                fichselection.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Veuillez selectionner patient ou praticien !");
 
    }//GEN-LAST:event_jContinuerActionPerformed

    private void jRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetourActionPerformed
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_jRetourActionPerformed

    private void jRetourMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRetourMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetourMouseDragged

    private void pfMotdepasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMotdepasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMotdepasseActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void rbPraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPraticienActionPerformed
        //on affiche les bouttons de mot de passe oublié de praticien
        jMDPpat.setVisible(false);
        tfMDPpat.setVisible(false);
        lbMDPpat.setVisible(false);
        jMDPprat.setVisible(true);
        tfMDPprat.setVisible(true);
        lbMDPprat.setVisible(true);
    }//GEN-LAST:event_rbPraticienActionPerformed

    private void rbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPatientActionPerformed
        //on affiche les bouttons de mot de passe oublié de patient
        jMDPpat.setVisible(true);
        tfMDPpat.setVisible(true);
        lbMDPpat.setVisible(true);
        jMDPprat.setVisible(false);
        tfMDPprat.setVisible(false);
        lbMDPprat.setVisible(false);

    }//GEN-LAST:event_rbPatientActionPerformed

    private void jMDPpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDPpatActionPerformed
        
        String social = tfMDPpat.getText();
        //JOptionPane.showMessageDialog(null, "Saisissez le numéro social associé à votre compte et l'identifiant de votre compte", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
        
        if(tfId.getText().length()==0 || social.length()==0){   //si il ne rentre pas tous les champs on affiche un msg
            JOptionPane.showMessageDialog(null, "Saisissez l'identifiant et le numero de telephone", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
        }
        if(tfId.getText().length()!=0 && social.length()!=0){
            if(User.recupererMDPpat(tfId.getText(), Integer.parseInt(social))==1){  //si il arrive à bien procéder alors on poursuit

                    JOptionPane.showMessageDialog(null, "Vous avez reussi vous connecter", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
                    fichselection = new Fselection(this, false, 1,User);
                    this.setVisible(false);
                    fichselection.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Vous n'avez pas reussi vous connecter", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMDPpatActionPerformed

    private void jMDPpratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDPpratActionPerformed
        
        String telephone = tfMDPprat.getText();
        
        if(tfId.getText().length()==0 || telephone.length()==0){    //si il ne rentre pas tous les champs on affiche un msg
            JOptionPane.showMessageDialog(null, "Saisissez l'identifiant et le numero de telephone", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
        }
        if(tfId.getText().length()!=0 && telephone.length()!=0){
            if(User.recupererMDPprat(tfId.getText(), Integer.parseInt(telephone))==1){  //si il arrive à bien procéder alors on poursuit

                    JOptionPane.showMessageDialog(null, "Vous avez reussi vous connecter", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
                    fichselection = new Fselection(this, false, 0,User);
                    this.setVisible(false);
                    fichselection.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vous n'avez pas reussi vous connecter", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMDPpratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fconnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fconnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fconnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fconnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fconnexion dialog = new Fconnexion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jConnexion;
    private javax.swing.JButton jContinuer;
    private javax.swing.JLabel jIdentifiant;
    private javax.swing.JButton jMDPpat;
    private javax.swing.JButton jMDPprat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jMotdepasse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jRetour;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbMDPpat;
    private javax.swing.JLabel lbMDPprat;
    private javax.swing.JPasswordField pfMotdepasse;
    private javax.swing.JRadioButton rbPatient;
    private javax.swing.JRadioButton rbPraticien;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMDPpat;
    private javax.swing.JTextField tfMDPprat;
    // End of variables declaration//GEN-END:variables
}
