/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFiches;

import javax.swing.JOptionPane;
import rdv_medicaux_sutharsan_ranjit.Utilisateurs;

/**
 *
 * @author Vithusan
 */
public class Fselection extends javax.swing.JDialog {

    /**
     * Creates new form Fselection
     */
    private int type=-1;
    private Utilisateurs User;
    public Fselection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Fselection(javax.swing.JDialog  parent, boolean modal,int type, Utilisateurs u) {
        super(parent, modal);
        initComponents();
        User = u;
        this.type=type;
    }
     public Fselection(javax.swing.JDialog  parent, boolean modal, Utilisateurs u) {
        super(parent, modal);
        initComponents();
        User = u;
       
    }
     public Fselection(java.awt.Frame parent, boolean modal, Utilisateurs u) {
        super(parent, modal);
        initComponents();
        User = u;
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbListprat = new javax.swing.JRadioButton();
        rbPriserdv = new javax.swing.JRadioButton();
        rbProposerrdv = new javax.swing.JRadioButton();
        jRetour = new javax.swing.JButton();
        jContinuer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbGeneraliste = new javax.swing.JRadioButton();
        rbSpecialiste = new javax.swing.JRadioButton();
        rbGeneralistebis = new javax.swing.JRadioButton();
        rbSpecialistebis = new javax.swing.JRadioButton();
        rbConsulter = new javax.swing.JRadioButton();
        rbPrise = new javax.swing.JRadioButton();
        rbAnnuler = new javax.swing.JRadioButton();
        rbConsulterRDV = new javax.swing.JRadioButton();
        rbAjouter = new javax.swing.JRadioButton();
        rbModif = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        tfName = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        tfNum = new javax.swing.JTextField();
        lbNum = new javax.swing.JLabel();
        lbVille = new javax.swing.JLabel();
        tfVille = new javax.swing.JTextField();
        rbAffiner = new javax.swing.JRadioButton();
        rbVoir = new javax.swing.JRadioButton();
        rbAnnulerRDV = new javax.swing.JRadioButton();
        tfSaisieDate = new javax.swing.JTextField();
        lbSaisieDate = new javax.swing.JLabel();
        tfSaisieNum = new javax.swing.JTextField();
        lbSaisieNum = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        rbListprat.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbListprat);
        rbListprat.setText("Consulter la liste de praticiens");
        rbListprat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbListpratActionPerformed(evt);
            }
        });

        rbPriserdv.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbPriserdv);
        rbPriserdv.setText("Prendre un rendez-vous");
        rbPriserdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPriserdvActionPerformed(evt);
            }
        });

        rbProposerrdv.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbProposerrdv);
        rbProposerrdv.setText("Gérer vos rendez-vous");
        rbProposerrdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProposerrdvActionPerformed(evt);
            }
        });

        jRetour.setBackground(new java.awt.Color(0, 102, 102));
        jRetour.setText("Retour");
        jRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetourActionPerformed(evt);
            }
        });

        jContinuer.setBackground(new java.awt.Color(0, 102, 102));
        jContinuer.setText("Continuer");
        jContinuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinuerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Que souhaitez- vous faire ?");

        rbGeneraliste.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(rbGeneraliste);
        rbGeneraliste.setText("Généraliste");

        rbSpecialiste.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup2.add(rbSpecialiste);
        rbSpecialiste.setText("Spécialiste");

        rbGeneralistebis.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup3.add(rbGeneralistebis);
        rbGeneralistebis.setText("Généraliste");
        rbGeneralistebis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeneralistebisActionPerformed(evt);
            }
        });

        rbSpecialistebis.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup3.add(rbSpecialistebis);
        rbSpecialistebis.setText("Spécialiste");
        rbSpecialistebis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSpecialistebisActionPerformed(evt);
            }
        });

        rbConsulter.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup4.add(rbConsulter);
        rbConsulter.setText("Consulter les RDV");
        rbConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbConsulterActionPerformed(evt);
            }
        });

        rbPrise.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup4.add(rbPrise);
        rbPrise.setText("Prendre un RDV");
        rbPrise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPriseActionPerformed(evt);
            }
        });

        rbAnnuler.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup4.add(rbAnnuler);
        rbAnnuler.setText("Annuler un RDV");
        rbAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAnnulerActionPerformed(evt);
            }
        });

        rbConsulterRDV.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(rbConsulterRDV);
        rbConsulterRDV.setText("Consulter vos RDV(s)");

        rbAjouter.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(rbAjouter);
        rbAjouter.setText("Ajouter un RDV");

        rbModif.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(rbModif);
        rbModif.setText("Modifier un RDV");

        jList1.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(jList1);

        lbName.setText("Saisissez le nom du praticien en question");

        lbNum.setText("Saisissez l'indice de la date ou la date");

        lbVille.setText("Saisissez la ville");

        tfVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVilleActionPerformed(evt);
            }
        });

        rbAffiner.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup6.add(rbAffiner);
        rbAffiner.setText("Affiner par ville");

        rbVoir.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup6.add(rbVoir);
        rbVoir.setText("Voir tous les praticiens");

        rbAnnulerRDV.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(rbAnnulerRDV);
        rbAnnulerRDV.setText("Annuler un RDV");

        lbSaisieDate.setText("Saisissez la date");

        lbSaisieNum.setText("Saisissez l'indice de la date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jContinuer)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbProposerrdv)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPriserdv)
                            .addComponent(rbListprat))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbAffiner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbVoir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbGeneralistebis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSpecialistebis))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbName)
                                    .addComponent(lbNum)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbGeneraliste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbSpecialiste))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfVille, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbVille))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbConsulterRDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbAjouter))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfSaisieNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(tfSaisieDate, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbSaisieDate)
                                            .addComponent(lbSaisieNum))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAnnulerRDV)
                                    .addComponent(rbModif)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbConsulter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbPrise)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbAnnuler))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbListprat)
                                    .addComponent(rbAffiner)
                                    .addComponent(rbVoir))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbGeneraliste)
                                    .addComponent(rbSpecialiste))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbVille))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbPriserdv)
                                    .addComponent(rbGeneralistebis)
                                    .addComponent(rbSpecialistebis))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbConsulter)
                                    .addComponent(rbPrise)
                                    .addComponent(rbAnnuler))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbProposerrdv)
                                    .addComponent(rbConsulterRDV)
                                    .addComponent(rbAjouter)
                                    .addComponent(rbModif)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAnnulerRDV)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSaisieDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSaisieDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRetour)
                        .addComponent(jContinuer)
                        .addComponent(lbSaisieNum))
                    .addComponent(tfSaisieNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Help");

        jMenuItem1.setText("Aide");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Sélectionnez votre choix pour accéder aux différentes fonctionnalités du site. Les visiteurs auront un accès limité du site, sinon quitter le site en allant dans Aide puis Quitter", "Message d'information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rbPriserdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPriserdvActionPerformed
        //on va afficher en fonction du boutton sélectionné, les boutons voulus.
        rbGeneraliste.setVisible(false);
        rbSpecialiste.setVisible(false);
        rbConsulterRDV.setVisible(false);
        rbAjouter.setVisible(false);
        rbModif.setVisible(false);
        rbAnnulerRDV.setVisible(false);
        lbSaisieDate.setVisible(false);
        tfSaisieDate.setVisible(false);
        lbSaisieNum.setVisible(false);
        tfSaisieNum.setVisible(false);
        rbGeneralistebis.setVisible(true);
        rbSpecialistebis.setVisible(true);
        tfName.setVisible(true);
       tfNum.setVisible(true);
       lbNum.setVisible(true);
       lbName.setVisible(true);
       rbAffiner.setVisible(false);
       rbVoir.setVisible(false);
       tfVille.setVisible(false);
       lbVille.setVisible(false);
    }//GEN-LAST:event_rbPriserdvActionPerformed

    private void jRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetourActionPerformed
        this.setVisible(false);
        this.getParent().setVisible(true);
    }//GEN-LAST:event_jRetourActionPerformed

    private void jContinuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinuerActionPerformed
        
        
        //selon les bouttons sélectionnées, on va utiliser le ou les méthodes qui lui sont associés
        String num = tfNum.getText();
        String date = tfSaisieDate.getText();
        String indice = tfSaisieNum.getText();
        
        if(rbGeneraliste.isSelected()==true){
            if(rbAffiner.isSelected()==false && rbVoir.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(rbAffiner.isSelected()==true){
               User.consulterPraticienVille(1, jList1, tfVille.getText());
                }
                if(rbVoir.isSelected()==true){
                     User.consulterPraticien(1, jList1);
                }
            }
           
        }
        
        else if(rbSpecialiste.isSelected()==true){
            if(rbAffiner.isSelected()==false && rbVoir.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(rbAffiner.isSelected()==true){
                    User.consulterPraticienVille(2, jList1, tfVille.getText());
                }
                if(rbVoir.isSelected()==true){ 
                    User.consulterPraticien(2, jList1);
                }
            }    
        }
        
        else if(rbPriserdv.isSelected()==true){
            if(rbSpecialistebis.isSelected()==false && rbGeneralistebis.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(rbGeneralistebis.isSelected()==true){
            if(rbConsulter.isSelected()==false && rbPrise.isSelected()==false && rbAnnuler.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(rbConsulter.isSelected()==true){
                    User.lookrdv(1, tfName.getText(), jList1);
                }
                if(rbPrise.isSelected()==true){
                    if(num.length()==0 || tfName.getText().length()==0){
                        JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date et le praticien en question", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
                    }
                    if(num.length()!=0 && tfName.getText().length()!=0){
                        User.prendrerdv(1, tfName.getText(), jList1, Integer.parseInt(num));
                    }
                }
                if(rbAnnuler.isSelected()==true){
                    if(num.length()==0 || tfName.getText().length()==0){
                        JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
                    }
                    if(num.length()!=0 && tfName.getText().length()!=0){
                        User.annulerRDV(1, tfName.getText(), jList1, Integer.parseInt(num));
                    }
                }
            }
            
        }   
        
        if(rbSpecialistebis.isSelected()==true){
            if(rbConsulter.isSelected()==false && rbPrise.isSelected()==false && rbAnnuler.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(rbConsulter.isSelected()==true){
                    User.lookrdv(2, tfName.getText(), jList1);
                }
                if(rbPrise.isSelected()==true){
                    if(num.length()==0){
                        JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
                    }
                    if(num.length()!=0){
                        User.prendrerdv(2, tfName.getText(), jList1, Integer.parseInt(num));
                    }
                }
                if(rbAnnuler.isSelected()==true){
                    if(num.length()==0){
                        JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
                    }
                    if(num.length()!=0){
                        User.annulerRDV(2, tfName.getText(), jList1, Integer.parseInt(num));
                    }
                }
            }
            
        }
        
        else if(rbProposerrdv.isSelected()==true){
            if(rbConsulterRDV.isSelected()==false && rbAjouter.isSelected()==false && rbModif.isSelected()==false && rbAnnulerRDV.isSelected()==false){
                JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(rbConsulterRDV.isSelected()==true){
            User.consulterSesRDV(jList1);
        }
        
        if(rbAjouter.isSelected()==true){
            if(date.length()==0){
                JOptionPane.showMessageDialog(null, "Saisissez la date souhaitée", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
            }
            if(date.length()!=0){
                User.ajouterRDV(jList1, Integer.parseInt(date));
            }
        }
        
        if(rbModif.isSelected()==true){
            if(date.length()==0 || indice.length()==0){
                JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date et la date souhaitée", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
            }
            if(date.length()!=0 || indice.length()!=0){
                User.modifierRDV(jList1, Integer.parseInt(indice), Integer.parseInt(date));
            }
        }
        
        if(rbAnnulerRDV.isSelected()==true){
            if(indice.length()==0){
                JOptionPane.showMessageDialog(null, "Saisissez l'indice de la date", "Message d'avertissement", JOptionPane.ERROR_MESSAGE);
            }
            if(indice.length()!=0){
                User.annulerRDV(jList1, Integer.parseInt(indice));
            }
        }
        
        else if(rbListprat.isSelected()==false && rbPriserdv.isSelected()==false && rbProposerrdv.isSelected()==false){
            JOptionPane.showMessageDialog(null, "Veuillez faire un choix", "Message d'information", JOptionPane.INFORMATION_MESSAGE);        
        }
    }//GEN-LAST:event_jContinuerActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       //on va afficher en fonction du boutton sélectionné, les boutons voulus.
        rbGeneraliste.setVisible(false);
        rbSpecialiste.setVisible(false);
        rbGeneralistebis.setVisible(false);
        rbSpecialistebis.setVisible(false);
        rbConsulter.setVisible(false);
        rbPrise.setVisible(false);
        rbAnnuler.setVisible(false);
        rbConsulterRDV.setVisible(false);
       rbAjouter.setVisible(false);
       rbModif.setVisible(false);
       rbAnnulerRDV.setVisible(false);
       lbSaisieDate.setVisible(false);
       tfSaisieDate.setVisible(false);
       lbSaisieNum.setVisible(false);
       tfSaisieNum.setVisible(false);
       tfName.setVisible(false);
       tfNum.setVisible(false);
       lbNum.setVisible(false);
       lbName.setVisible(false);
       rbAffiner.setVisible(false);
       rbVoir.setVisible(false);
       tfVille.setVisible(false);
       lbVille.setVisible(false);
        if (type==-1){  //si c'est un visiteur
           rbPriserdv.setVisible(false);
           rbProposerrdv.setVisible(false);    
       }
        else if(type ==1){  //si c'est un patient
            rbProposerrdv.setVisible(false);
        }
       if(rbPriserdv.isSelected()==true){
           rbGeneralistebis.setVisible(true);
           rbSpecialistebis.setVisible(true);
           tfName.setVisible(true);
           tfNum.setVisible(true);
           lbNum.setVisible(true);
           lbName.setVisible(true);
       }
    }//GEN-LAST:event_formWindowActivated

    private void rbListpratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbListpratActionPerformed
       //on va afficher en fonction du boutton sélectionné, les boutons voulus.
        rbGeneraliste.setVisible(true);
       rbSpecialiste.setVisible(true);
       rbAffiner.setVisible(true);
       rbVoir.setVisible(true);
       tfVille.setVisible(true);
       lbVille.setVisible(true);
       rbGeneralistebis.setVisible(false);
       rbSpecialistebis.setVisible(false);
       rbConsulter.setVisible(false);
       rbPrise.setVisible(false);
       rbAnnuler.setVisible(false);
       rbConsulterRDV.setVisible(false);
       rbAjouter.setVisible(false);
       rbModif.setVisible(false);
       rbAnnulerRDV.setVisible(false);
       lbSaisieDate.setVisible(false);
       tfSaisieDate.setVisible(false);
       lbSaisieNum.setVisible(false);
       tfSaisieNum.setVisible(false);
       tfName.setVisible(false);
       tfNum.setVisible(false);
       lbNum.setVisible(false);
       lbName.setVisible(false);
    }//GEN-LAST:event_rbListpratActionPerformed

    private void rbProposerrdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProposerrdvActionPerformed
       //on va afficher en fonction du boutton sélectionné, les boutons voulus.
        rbGeneraliste.setVisible(false);
       rbSpecialiste.setVisible(false);
       rbGeneralistebis.setVisible(false);
       rbSpecialistebis.setVisible(false);
       rbConsulter.setVisible(false);
       rbPrise.setVisible(false);
       rbAnnuler.setVisible(false);
       rbConsulterRDV.setVisible(true);
       rbAjouter.setVisible(true);
       rbModif.setVisible(true);
       rbAnnulerRDV.setVisible(true);
       lbSaisieDate.setVisible(true);
       tfSaisieDate.setVisible(true);
       lbSaisieNum.setVisible(true);
       tfSaisieNum.setVisible(true);
       tfName.setVisible(false);
       tfNum.setVisible(false);
       lbNum.setVisible(false);
       lbName.setVisible(false);
       rbAffiner.setVisible(false);
       rbVoir.setVisible(false);
       tfVille.setVisible(false);
       lbVille.setVisible(false);
    }//GEN-LAST:event_rbProposerrdvActionPerformed

    private void rbGeneralistebisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeneralistebisActionPerformed
        //on va afficher les différents bouttons 
        if(rbGeneralistebis.isSelected()==true){
            rbConsulter.setVisible(true);
            rbPrise.setVisible(true);
            rbAnnuler.setVisible(true);
        }
    }//GEN-LAST:event_rbGeneralistebisActionPerformed

    private void rbSpecialistebisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSpecialistebisActionPerformed
        //on va afficher les différents bouttons
        if(rbSpecialistebis.isSelected()==true){
            rbConsulter.setVisible(true);
            rbPrise.setVisible(true);
            rbAnnuler.setVisible(true);
        }
    }//GEN-LAST:event_rbSpecialistebisActionPerformed

    private void rbConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbConsulterActionPerformed

    }//GEN-LAST:event_rbConsulterActionPerformed

    private void rbPriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPriseActionPerformed

    }//GEN-LAST:event_rbPriseActionPerformed

    private void rbAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAnnulerActionPerformed

    }//GEN-LAST:event_rbAnnulerActionPerformed

    private void tfVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fselection dialog = new Fselection(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jContinuer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRetour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbSaisieDate;
    private javax.swing.JLabel lbSaisieNum;
    private javax.swing.JLabel lbVille;
    private javax.swing.JRadioButton rbAffiner;
    private javax.swing.JRadioButton rbAjouter;
    private javax.swing.JRadioButton rbAnnuler;
    private javax.swing.JRadioButton rbAnnulerRDV;
    private javax.swing.JRadioButton rbConsulter;
    private javax.swing.JRadioButton rbConsulterRDV;
    private javax.swing.JRadioButton rbGeneraliste;
    private javax.swing.JRadioButton rbGeneralistebis;
    private javax.swing.JRadioButton rbListprat;
    private javax.swing.JRadioButton rbModif;
    private javax.swing.JRadioButton rbPrise;
    private javax.swing.JRadioButton rbPriserdv;
    private javax.swing.JRadioButton rbProposerrdv;
    private javax.swing.JRadioButton rbSpecialiste;
    private javax.swing.JRadioButton rbSpecialistebis;
    private javax.swing.JRadioButton rbVoir;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNum;
    private javax.swing.JTextField tfSaisieDate;
    private javax.swing.JTextField tfSaisieNum;
    private javax.swing.JTextField tfVille;
    // End of variables declaration//GEN-END:variables
}
